# Chapter 2 — Supervised Learning

## Introduction to Machine Learning with Python

**Book:** Introduction to Machine Learning with Python  
**Authors:** Andreas C. Müller & Sarah Guido

## 1. Chapter Overview

Chapter ini membahas supervised learning secara lebih mendalam.

Supervised learning merupakan pendekatan Machine Learning yang
digunakan untuk mempelajari hubungan antara input dan target
berdasarkan data yang telah memiliki label.

Chapter ini membahas dua permasalahan utama dalam supervised
learning, yaitu classification dan regression.

Selain itu, chapter ini memperkenalkan beberapa algoritma
supervised learning seperti K-Nearest Neighbors, linear models,
Naive Bayes, decision trees, ensemble methods, kernelized
support vector machines, dan neural networks.

Chapter ini juga membahas konsep generalization, overfitting,
underfitting, serta uncertainty estimates pada classification.

## 2. Learning Objectives

Setelah mempelajari chapter ini, tujuan pembelajaran yang ingin
dicapai adalah:

1. Memahami konsep supervised learning.
2. Membedakan classification dan regression.
3. Memahami konsep generalization, overfitting, dan underfitting.
4. Memahami cara kerja beberapa algoritma supervised learning.
5. Mengimplementasikan K-Nearest Neighbors.
6. Mengimplementasikan linear models.
7. Mengenal Naive Bayes.
8. Mengimplementasikan decision trees dan ensemble methods.
9. Mengenal kernelized Support Vector Machines.
10. Mengenal neural networks untuk supervised learning.
11. Memahami decision function dan probability estimates.
12. Membandingkan karakteristik beberapa algoritma supervised learning.

## 3. Classification and Regression

Supervised learning memiliki dua jenis permasalahan utama, yaitu
classification dan regression.

### 3.1 Classification

Classification merupakan permasalahan Machine Learning ketika
target yang ingin diprediksi berupa kategori atau class.

Contohnya adalah menentukan apakah sebuah email termasuk spam
atau bukan spam.

Classification dapat dibagi menjadi:

- Binary classification: memiliki dua kelas.
- Multiclass classification: memiliki lebih dari dua kelas.

Contoh binary classification adalah menentukan apakah email
merupakan spam atau bukan spam.

Contoh multiclass classification adalah menentukan jenis bunga
Iris berdasarkan karakteristik bunganya.

### 3.2 Regression

Regression digunakan ketika target yang ingin diprediksi berupa
nilai numerik atau kontinu.

Contohnya adalah memprediksi harga rumah berdasarkan luas,
jumlah kamar, lokasi, dan karakteristik lainnya.

Berbeda dengan classification yang menghasilkan kategori,
regression menghasilkan nilai numerik.

## 4. Generalization, Overfitting, and Underfitting

Tujuan utama Machine Learning bukan hanya menghasilkan performa
yang tinggi pada training data, tetapi menghasilkan model yang
dapat bekerja dengan baik pada data baru.

Kemampuan model untuk bekerja dengan baik pada data yang belum
pernah dilihat sebelumnya disebut generalization.

### 4.1 Overfitting

Overfitting terjadi ketika model terlalu kompleks sehingga
terlalu menyesuaikan diri dengan training data.

Model dapat menghasilkan performa sangat baik pada training data,
tetapi performanya menurun ketika diberikan data baru.

Secara sederhana:

Training performance → sangat tinggi
Testing performance  → lebih rendah

### 4.2 Underfitting

Underfitting terjadi ketika model terlalu sederhana untuk
menangkap pola yang terdapat dalam data.

Akibatnya, performa model dapat rendah baik pada training maupun
testing data.

### 4.3 Generalization

Generalization menunjukkan kemampuan model untuk menghasilkan
prediksi yang baik pada data baru.

Model yang baik tidak hanya menghafalkan training data, tetapi
mampu mempelajari pola yang dapat diterapkan pada data yang
belum pernah dilihat.

## 5. Sample Datasets

Untuk memahami berbagai algoritma supervised learning, kita
akan menggunakan beberapa dataset yang tersedia pada
scikit-learn.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [2]:
iris = load_iris()

X = iris.data
y = iris.target

print("Feature shape:", X.shape)
print("Target shape:", y.shape)
print("Target names:", iris.target_names)

Feature shape: (150, 4)
Target shape: (150,)
Target names: ['setosa' 'versicolor' 'virginica']


### Explanation

Dataset Iris digunakan untuk permasalahan classification.

`X` berisi fitur yang digunakan sebagai input model, sedangkan
`y` berisi target atau kelas bunga.

Dataset ini memiliki beberapa fitur karakteristik bunga dan
tiga kelas target.

## 6. K-Nearest Neighbors

K-Nearest Neighbors atau KNN merupakan algoritma yang membuat
prediksi berdasarkan sejumlah data training yang memiliki jarak
paling dekat dengan data yang akan diprediksi.

Jumlah tetangga yang digunakan ditentukan oleh parameter `k`
atau `n_neighbors`.

Nilai k yang kecil membuat model lebih sensitif terhadap data
di sekitarnya, sedangkan nilai k yang lebih besar membuat
keputusan model lebih dipengaruhi oleh lebih banyak data.

In [4]:
from sklearn.neighbors import KNeighborsClassifier

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    random_state=0
)

knn = KNeighborsClassifier(n_neighbors=3)

knn.fit(X_train, y_train)

print("Training accuracy:", knn.score(X_train, y_train))
print("Testing accuracy:", knn.score(X_test, y_test))

Training accuracy: 0.9642857142857143
Testing accuracy: 0.9736842105263158


### Explanation

`KNeighborsClassifier` digunakan untuk membangun model KNN
classification.

Parameter `n_neighbors=3` berarti model menggunakan tiga
tetangga terdekat ketika menentukan kelas suatu data.

Method `fit()` digunakan untuk menyiapkan model berdasarkan
training data.

Method `score()` digunakan untuk mengukur akurasi model.

In [5]:
from sklearn.datasets import make_regression
from sklearn.neighbors import KNeighborsRegressor

X_reg, y_reg = make_regression(
    n_samples=100,
    n_features=1,
    noise=20,
    random_state=42
)

X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(
    X_reg,
    y_reg,
    random_state=0
)

knn_reg = KNeighborsRegressor(n_neighbors=3)

knn_reg.fit(X_train_reg, y_train_reg)

print("Training R²:", knn_reg.score(X_train_reg, y_train_reg))
print("Testing R²:", knn_reg.score(X_test_reg, y_test_reg))

Training R²: 0.9101899491879297
Testing R²: 0.7189151729634986


### KNN Regression

Pada regression, KNN memprediksi nilai numerik berdasarkan
nilai target dari beberapa tetangga terdekat.

Berbeda dengan classification yang menghasilkan kelas,
KNN regression menghasilkan nilai kontinu.

Pada contoh ini performa regression diukur menggunakan R² score.

### KNN Regression

Pada regression, KNN memprediksi nilai numerik berdasarkan
nilai target dari beberapa tetangga terdekat.

Berbeda dengan classification yang menghasilkan kelas,
KNN regression menghasilkan nilai kontinu.

Pada contoh ini performa regression diukur menggunakan R² score.

In [6]:
from sklearn.linear_model import LinearRegression

linear_model = LinearRegression()

linear_model.fit(X_train_reg, y_train_reg)

print("Training R²:",
      linear_model.score(X_train_reg, y_train_reg))

print("Testing R²:",
      linear_model.score(X_test_reg, y_test_reg))

Training R²: 0.8779348171187852
Testing R²: 0.7646804229836157


### Explanation

`LinearRegression` digunakan untuk memodelkan hubungan linear
antara input dan target.

Model mempelajari koefisien yang menentukan seberapa besar
pengaruh setiap fitur terhadap target.

Performa model dapat dilihat menggunakan R² score.

### 7.1 Ridge Regression

Ridge Regression merupakan variasi dari linear regression
yang menggunakan regularization.

Regularization digunakan untuk mengurangi kompleksitas model
dan membantu mengurangi risiko overfitting.

Parameter utama Ridge adalah `alpha`.

Semakin besar nilai alpha, semakin kuat regularization yang
diberikan pada model.

In [7]:
from sklearn.linear_model import Ridge

ridge = Ridge(alpha=1.0)

ridge.fit(X_train_reg, y_train_reg)

print("Training R²:", ridge.score(X_train_reg, y_train_reg))
print("Testing R²:", ridge.score(X_test_reg, y_test_reg))

Training R²: 0.877686627797938
Testing R²: 0.7686960436871374


### 7.2 Logistic Regression

Logistic Regression merupakan linear model yang dapat digunakan
untuk classification.

Model menghasilkan nilai yang kemudian digunakan untuk
menentukan class suatu data.

In [8]:
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression(max_iter=1000)

logreg.fit(X_train, y_train)

print("Training accuracy:", logreg.score(X_train, y_train))
print("Testing accuracy:", logreg.score(X_test, y_test))

Training accuracy: 0.9821428571428571
Testing accuracy: 0.9736842105263158


## 8. Naive Bayes Classifiers

Naive Bayes merupakan kelompok algoritma classification yang
berdasarkan pada Bayes' theorem.

Algoritma ini menggunakan asumsi bahwa fitur-fitur tertentu
bersifat independen satu sama lain berdasarkan class.

Naive Bayes sering digunakan karena sederhana dan relatif cepat,
terutama pada data dengan jumlah fitur yang besar.

In [9]:
from sklearn.naive_bayes import GaussianNB

nb = GaussianNB()

nb.fit(X_train, y_train)

print("Training accuracy:", nb.score(X_train, y_train))
print("Testing accuracy:", nb.score(X_test, y_test))

Training accuracy: 0.9464285714285714
Testing accuracy: 1.0


### Explanation

`GaussianNB` merupakan implementasi Gaussian Naive Bayes.

Model mempelajari distribusi fitur pada setiap class dan
menggunakannya untuk menentukan class yang paling mungkin
untuk suatu data baru.

## 9. Decision Trees

Decision Tree merupakan algoritma yang melakukan prediksi
menggunakan struktur seperti pohon keputusan.

Data secara bertahap dibagi berdasarkan kondisi tertentu
hingga mencapai suatu keputusan atau prediction.

Decision tree dapat digunakan untuk classification maupun
regression.

In [10]:
from sklearn.tree import DecisionTreeClassifier

tree = DecisionTreeClassifier(
    max_depth=3,
    random_state=0
)

tree.fit(X_train, y_train)

print("Training accuracy:", tree.score(X_train, y_train))
print("Testing accuracy:", tree.score(X_test, y_test))

Training accuracy: 0.9821428571428571
Testing accuracy: 0.9736842105263158


### Explanation

Parameter `max_depth` menentukan kedalaman maksimum decision
tree.

Tree yang terlalu dalam dapat menjadi sangat kompleks dan
berpotensi mengalami overfitting.

Pembatasan kedalaman dapat digunakan untuk mengontrol kompleksitas
model.

## 10. Ensembles of Decision Trees

Ensemble methods menggabungkan beberapa model untuk menghasilkan
prediksi yang lebih kuat dibandingkan hanya menggunakan satu
model.

Salah satu contoh ensemble yang dibahas adalah Random Forest.

Random Forest terdiri dari banyak decision tree yang kemudian
digabungkan untuk menghasilkan prediksi.

In [11]:
from sklearn.ensemble import RandomForestClassifier

forest = RandomForestClassifier(
    n_estimators=100,
    random_state=0
)

forest.fit(X_train, y_train)

print("Training accuracy:", forest.score(X_train, y_train))
print("Testing accuracy:", forest.score(X_test, y_test))

Training accuracy: 1.0
Testing accuracy: 0.9736842105263158


### Explanation

`n_estimators` menunjukkan jumlah decision tree yang digunakan
dalam Random Forest.

Random Forest menggabungkan prediksi dari banyak tree sehingga
model tidak hanya bergantung pada satu decision tree.

### 10.1 Gradient Boosting

Gradient Boosting membangun model secara bertahap.

Setiap model berikutnya berusaha memperbaiki kesalahan yang
dihasilkan oleh model-model sebelumnya.

Pendekatan ini dapat menghasilkan model dengan performa yang
tinggi, tetapi parameter model perlu dikontrol agar tidak
mengalami overfitting.

In [12]:
from sklearn.ensemble import GradientBoostingClassifier

gbrt = GradientBoostingClassifier(
    random_state=0
)

gbrt.fit(X_train, y_train)

print("Training accuracy:", gbrt.score(X_train, y_train))
print("Testing accuracy:", gbrt.score(X_test, y_test))

Training accuracy: 1.0
Testing accuracy: 0.9736842105263158


## 11. Kernelized Support Vector Machines

Support Vector Machine atau SVM merupakan algoritma yang dapat
digunakan untuk classification maupun regression.

Kernelized SVM memungkinkan model menangani hubungan yang
bersifat non-linear dengan menggunakan fungsi kernel.

Salah satu kernel yang umum digunakan adalah RBF atau Radial
Basis Function.

In [13]:
from sklearn.svm import SVC

svc = SVC(
    kernel='rbf',
    C=1.0,
    gamma='scale'
)

svc.fit(X_train, y_train)

print("Training accuracy:", svc.score(X_train, y_train))
print("Testing accuracy:", svc.score(X_test, y_test))

Training accuracy: 0.9642857142857143
Testing accuracy: 0.9736842105263158


### Important Parameters

#### C

Parameter `C` mengontrol seberapa besar model memberikan
penalti terhadap kesalahan klasifikasi.

Nilai C yang lebih besar membuat model berusaha lebih keras
untuk mengklasifikasikan training data dengan benar.

#### gamma

Pada RBF kernel, `gamma` mengontrol seberapa jauh pengaruh
sebuah data training.

Gamma yang tinggi dapat menghasilkan model yang lebih kompleks,
sedangkan gamma yang rendah menghasilkan pengaruh yang lebih luas.

## 12. Neural Networks

Neural network merupakan model yang terinspirasi dari struktur
jaringan neuron dan dapat digunakan untuk mempelajari hubungan
yang kompleks antara input dan target.

Pada scikit-learn, salah satu implementasinya adalah
Multi-Layer Perceptron atau MLP.

In [14]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(
    hidden_layer_sizes=(10,),
    max_iter=1000,
    random_state=0
)

mlp.fit(X_train, y_train)

print("Training accuracy:", mlp.score(X_train, y_train))
print("Testing accuracy:", mlp.score(X_test, y_test))

Training accuracy: 0.9821428571428571
Testing accuracy: 0.9736842105263158


/usr/local/lib/python3.13/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


### Explanation

`MLPClassifier` digunakan untuk membangun neural network
classification.

Parameter `hidden_layer_sizes` menentukan jumlah neuron pada
hidden layer.

Pada contoh ini digunakan satu hidden layer dengan 10 neuron.

`max_iter` menentukan jumlah maksimum iterasi selama proses
training.

## 13. Uncertainty Estimates from Classifiers

Selain menghasilkan class prediction, beberapa model
classification juga dapat memberikan informasi mengenai
seberapa yakin model terhadap suatu prediction.

Dua pendekatan yang dibahas adalah:

1. Decision function
2. Probability estimates

In [15]:
decision_values = svc.decision_function(X_test)

print(decision_values[:5])

[[-0.24219161  1.10820643  2.22840137]
 [-0.21486166  2.24041311  0.85459832]
 [ 2.23379995  1.14491815 -0.25238991]
 [-0.22930408  0.88161501  2.2445625 ]
 [ 2.23094366  1.15674715 -0.25288001]]


### 13.1 Decision Function

`decision_function()` memberikan nilai yang menunjukkan posisi
suatu data terhadap decision boundary model.

Nilai tersebut dapat digunakan untuk mengetahui seberapa jauh
data dari batas keputusan.

In [16]:
svc_prob = SVC(
    kernel='rbf',
    probability=True,
    random_state=0
)

svc_prob.fit(X_train, y_train)

probabilities = svc_prob.predict_proba(X_test)

print(probabilities[:5])

[[0.00895819 0.03005968 0.96098213]
 [0.00943416 0.98034517 0.01022067]
 [0.96945805 0.01830945 0.01223251]
 [0.00941197 0.00441037 0.98617765]
 [0.96296699 0.0253645  0.01166851]]


### 13.2 Probability Estimates

`predict_proba()` menghasilkan estimasi probabilitas untuk setiap
class.

Setiap baris menunjukkan probabilitas bahwa suatu data termasuk
ke masing-masing class.

Nilai probabilitas dapat digunakan untuk melihat tingkat
keyakinan model terhadap prediction.

In [17]:
predictions = svc_prob.predict(X_test)

print(predictions[:10])

[2 1 0 2 0 2 0 1 1 1]


### 13.3 Multiclass Classification

Pada multiclass classification, model harus memilih satu class
dari lebih dari dua kemungkinan.

Dataset Iris merupakan contoh multiclass classification karena
memiliki tiga jenis bunga sebagai target.

In [18]:
models = {
    "KNN": KNeighborsClassifier(n_neighbors=3),
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Naive Bayes": GaussianNB(),
    "Decision Tree": DecisionTreeClassifier(max_depth=3, random_state=0),
    "Random Forest": RandomForestClassifier(n_estimators=100, random_state=0),
    "Gradient Boosting": GradientBoostingClassifier(random_state=0),
    "SVM": SVC(),
    "Neural Network": MLPClassifier(
        hidden_layer_sizes=(10,),
        max_iter=1000,
        random_state=0
    )
}

results = []

for name, model in models.items():
    model.fit(X_train, y_train)
    train_score = model.score(X_train, y_train)
    test_score = model.score(X_test, y_test)

    results.append({
        "Model": name,
        "Training Accuracy": train_score,
        "Testing Accuracy": test_score
    })

results_df = pd.DataFrame(results)

results_df

/usr/local/lib/python3.13/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


,Model,Training Accuracy,Testing Accuracy
0,KNN,0.964286,0.973684
1,Logistic Regression,0.982143,0.973684
2,Naive Bayes,0.946429,1.000000
3,Decision Tree,0.982143,0.973684
4,Random Forest,1.000000,0.973684
5,Gradient Boosting,1.000000,0.973684
6,SVM,0.964286,0.973684
7,Neural Network,0.982143,0.973684


## 14. Results and Analysis

Beberapa algoritma supervised learning telah diimplementasikan
dan diuji menggunakan dataset Iris.

Perbedaan antara training accuracy dan testing accuracy dapat
digunakan sebagai salah satu indikasi bagaimana model melakukan
generalization.

Model dengan training accuracy yang sangat tinggi tetapi testing
accuracy yang jauh lebih rendah dapat menunjukkan indikasi
overfitting.

Sebaliknya, apabila performa training dan testing sama-sama
rendah, model mungkin terlalu sederhana sehingga mengalami
underfitting.

Perlu diperhatikan bahwa nilai accuracy pada contoh ini
bergantung pada pembagian training dan testing data yang
digunakan. Oleh karena itu, perbandingan model pada satu
pembagian data tidak cukup untuk menyimpulkan bahwa suatu model
selalu lebih baik daripada model lainnya.

## 14.1 Comparison of Supervised Learning Algorithms

| Algorithm | Main Use | Main Characteristic |
|---|---|---|
| KNN | Classification & Regression | Berdasarkan tetangga terdekat |
| Linear Models | Classification & Regression | Hubungan linear |
| Naive Bayes | Classification | Probabilistic approach |
| Decision Tree | Classification & Regression | Struktur pohon keputusan |
| Random Forest | Classification & Regression | Gabungan banyak decision tree |
| Gradient Boosting | Classification & Regression | Model dibangun secara bertahap |
| Kernelized SVM | Classification & Regression | Dapat menangani pola non-linear |
| Neural Network | Classification & Regression | Mempelajari hubungan kompleks |

# 15. Chapter Summary

Chapter ini membahas supervised learning secara lebih mendalam,
khususnya classification dan regression.

Pembahasan dimulai dengan konsep generalization, overfitting,
dan underfitting yang penting dalam menentukan kemampuan model
untuk bekerja pada data baru.

Beberapa algoritma supervised learning kemudian diperkenalkan,
yaitu K-Nearest Neighbors, linear models, Naive Bayes, decision
trees, ensemble methods, kernelized Support Vector Machines,
dan neural networks.

Chapter ini juga memperkenalkan uncertainty estimates melalui
decision function dan probability estimates.

Dari implementasi berbagai model dapat dipahami bahwa setiap
algoritma memiliki cara kerja, parameter, kelebihan, dan
keterbatasan yang berbeda.

# 16. Key Takeaways

- Supervised learning menggunakan data yang memiliki target.
- Classification menghasilkan kategori atau class.
- Regression menghasilkan nilai numerik.
- Generalization merupakan kemampuan model bekerja pada data baru.
- Overfitting terjadi ketika model terlalu menyesuaikan diri
  dengan training data.
- Underfitting terjadi ketika model terlalu sederhana.
- KNN menggunakan data terdekat untuk membuat prediction.
- Linear models memodelkan hubungan linear.
- Naive Bayes menggunakan pendekatan probabilistik.
- Decision tree menggunakan struktur keputusan berbentuk pohon.
- Ensemble methods menggabungkan beberapa model.
- Kernelized SVM dapat digunakan untuk pola non-linear.
- Neural networks dapat mempelajari hubungan yang kompleks.
- Classifier dapat memberikan prediction dan informasi
  uncertainty.

# 17. Reference

Müller, A. C., & Guido, S. (2017).
*Introduction to Machine Learning with Python:
A Guide for Data Scientists*.
O'Reilly Media.

Official author repository:
https://github.com/amueller/introduction_to_ml_with_python